apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-root
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: dev
    repoURL: git@github.com:borovetsdmytro/Automat-IT-Argo.git
    targetRevision: HEAD