apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-dev
  namespace: argo-cd
spec:
  project: default
  source:
    chart: apache
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 9.0.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dev