apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2-dev
  namespace: argo-cd
spec:
  project: default
  source:
    chart: apache
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.0.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true